[package]
name = "bft-bench-core"
version = "0.0.1"
edition = "2021"
authors = ["Fabio Tudone <fabtud@gmail.com>"]

[dependencies]
async-trait = "0.1.71"
bytes = "1.4.0"
histogram = "0.7.3"
log = "0.4.19"
rand = "0.8.5"
serde = "1.0.171"
serde_derive = "1.0.171"
serde_json = "1.0.103"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
uuid = { version = "1.4.1", features = ["v4"] }
