[package]
name = "bft-bench-core"
version = "0.0.1"
edition = "2021"
authors = ["Fabio Tudone <fabtud@gmail.com>"]

[dependencies]
async-trait = "0.1.58"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "sync", "time"] }
uuid = { version = "1.2.0", features = ["v4"] }
bytes = "1.3.0"
rand = "0.7.3"
serde = "1.0.147"
serde_derive = "1.0.147"
confy = "0.5.1"
log = "0.4"
histogram = "0.6.9"
indoc = "1.0.7"
