[package]
name = "bft-bench-core"
version = "0.0.1"
edition = "2021"
authors = ["Fabio Tudone <fabtud@gmail.com>"]

[dependencies]
async-trait = "0.1.68"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
uuid = { version = "1.3.2", features = ["v4"] }
bytes = "1.4.0"
rand = "0.8.5"
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
log = "0.4.17"
histogram = "0.7.2"
