[package]
name = "bft-bench-core"
version = "0.0.1"
edition = "2021"
authors = ["Fabio Tudone <fabtud@gmail.com>"]

[dependencies.async-trait]
version = "0.1.58"

[dependencies.tokio]
version = "1.21.2"
features = ["rt-multi-thread", "time", "sync"]

[dependencies.uuid]
version = "1.2.0"
features = ["v4"]

[dependencies.bytes]
version = "1.3.0"

[dependencies.rand]
version = "0.7.3"

[dependencies.serde]
version = "1.0.147"

[dependencies.serde_derive]
version = "1.0.147"

[dependencies.confy]
version = "0.5.1"

[dependencies.log]
version = "0.4"

[dependencies.histogram]
version = "0.6.9"

[dependencies.indoc]
version = "1.0.7"
