transaction_size=20000

[run_duration]
secs=60
nanos=0

[report_interval]
secs=10
nanos=0

[write_interval]
secs=0
nanos=33333

[read_grace]
secs=30
nanos=0

[[nodes]]
[nodes.ReadWrite.node.endpoint]
host = "localhost"
port = 50051
